"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9gdo=^nl)8375h))zrg99eslii27=x3(wxaa0u!)$(3#z2%ct_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'



# JAZZMIN SETTINGS (Theme & Layout)
JAZZMIN_SETTINGS = {
    # Titles and Branding
    "site_title": "TidyTracker Admin",
    "site_header": "TidyTracker",
    "site_brand": "TidyTracker",
    "welcome_sign": "Welcome to the TidyTracker Command Center",
    "custom_links": {
        "main": [
            {
                "name": "Generate Schedule", 
                "url": "generate_schedule", # This must match the name in your urls.py
                "icon": "fas fa-calendar-plus",
            },
            {
                "name": "User Dashboard", 
                "url": "home", # This must match the name in your urls.py
                "icon": "fas fa-arrow-left",
            }
        ]
    },

    "custom_js": "js/admin_custom.js",  # JavaScript for admin view customizations

    # The Menu Icons (FontAwesome 5)
    "icons": {
        # Default Auth apps
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Custom Models
        "main.Chore": "fas fa-broom",                
        "main.AssignedChore": "fas fa-clipboard-check", 
        "main.UserStats": "fas fa-chart-line",
    },

    # Sidebar Organization
    # This forces 'main' app to appear at the top of the sidebar
    "order_with_respect_to": ["main", "auth"],

    # User Menu (Link back to Dashboard)
    "usermenu_links": [
        {"name": "User Dashboard", "url": "home", "icon": "fas fa-home"}, 
    ],

    # UI Builder
    # Theme Builder button in the admin
    "show_ui_builder": True, 
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",   # flatly, darkly, slate, solar, cyborg
    #"theme": "darkly", # Dark Mode
}
