# Generated by Django 6.0.1 on 2026-02-18 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userstats_options_choreextensionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreextensionrequest',
            name='new_due_date',
        ),
        migrations.RemoveField(
            model_name='choreextensionrequest',
            name='requested_extension_days',
        ),
        migrations.AddField(
            model_name='choreextensionrequest',
            name='requested_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
