# Generated by Django 6.0.1 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_choreextensionrequest_new_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreextensionrequest',
            name='requested_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
